### PR TITLE
Add GitHub actions for Firebase deployment. Add build folder to .gitignore.

### PR DESCRIPTION
**Pull request by joelkek**

### CODE REVIEW

**Comment by gauravkeerthi** [comment]
It said all checks have failed. I'm not familiar with github actions to deploy. Should I wait for you to fix it or merge first?

**Comment by ravern** [comment]
@gauravkeerthi you can click on "Details" of the failing action to view the console output to diagnose why it failed. In this case, it seems like the TypeScript compiler is running. Do we have TypeScript in this app?

image

**Comment by gauravkeerthi** [comment]
We do not have typescript anywhere I can find / think of. How?

**Comment by joelkek** [comment]
Alright I've removed the typescript library since it was causing errors.
Best practice would have been to raise a separate PR for the typescript library removal, but I'm skipping that step and combining it into this one.

**Pull request merged**
